server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/camilo4182/department-users-app-config-server
          clone-on-start: true